		warrior.born();
		$("#born").click(function(){
			warrior.born();
		});
		$("#takeSword").click(function(){
			warrior.takeSword();
		});
		$("#go").click(function(){
			warrior.go();
		});
		$("#back").click(function(){
			warrior.back();
		});
		$("#shield").click(function(){
			warrior.shield();
		});
		$("#hit").click(function(){
			warrior.hit();
		});
		$("#upHit").click(function(){
			warrior.upHit();
		});	